from . import ir_ui_view
from . import is_dashboard
from . import is_dashboard_parameter
from . import is_dashboard_widget
from . import is_dashboard_widget_template
from . import is_dashboard_widget_type
from . import is_dashboard__add_item_wizard
from . import is_dashboard_sound
from . import is_dashboard_widget_tag
from . import is_dashboard_widget_notes
from . import is_dashboard_data
from . import is_dashboard_datasource_query
from . import is_dashboard_datasource_sql
from . import is_dashboard_widget_card
from . import is_dashboard_widget_config_date
from . import is_dashboard_widget_export
from . import is_dashboard_widget_goal
from . import is_dashboard_widget_goal_line
from . import is_dashboard_widget_graph
from . import is_dashboard_widget_graph_chartjs
from . import is_dashboard_widget_graph_chartjs_bar
from . import is_dashboard_widget_graph_chartjs_line
from . import is_dashboard_widget_graph_chartjs_pie
from . import is_dashboard_widget_graph_chartjs_radar
from . import is_dashboard_widget_html
from . import is_dashboard_widget_table
from . import is_dashboard_widget_record_list
from . import is_dashboard_widget_action
from . import is_dashboard_datasource_python
from . import res_partner
from . import is_dashboard_email
from . import is_dashboard_widget_position
from . import is_dashboard_user_data
from . import is_dashboard_widget_group_security
from . import is_dashboard_widget__group_security
