# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.4.0
_src_path: git+https://github.com/OCA/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 14.0
rebel_module_groups: []
repo_description: null
repo_name: MIS Builder
repo_slug: mis-builder
travis_apt_packages: []
travis_apt_sources: []
