from . import fsm_order
from . import fsm_activity
from . import res_partner
from . import fsm_template
from . import fsm_equipment
from . import fsm_person
from . import fsm_recurring
from . import fsm_recurring_template
from . import sale_order_line
from . import fsm_location
from . import fsm_note
